[2025-05-21 08:35:33 -0400] [28103] [INFO] Starting gunicorn 21.2.0
[2025-05-21 08:35:33 -0400] [28103] [INFO] Listening at: http://0.0.0.0:5000 (28103)
[2025-05-21 08:35:33 -0400] [28103] [INFO] Using worker: sync
[2025-05-21 08:35:33 -0400] [28104] [INFO] Booting worker with pid: 28104
[2025-05-21 08:35:33 -0400] [28104] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.11/dist-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.11/dist-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/prototipo_web/recursosweb/wsgi.py", line 9, in <module>
    from src.routes.visualizacion import visualizacion_bp
  File "/home/ubuntu/prototipo_web/recursosweb/src/routes/visualizacion.py", line 3, in <module>
    from src.models.asistencia import AsistenciaHistorica
ImportError: cannot import name 'AsistenciaHistorica' from 'src.models.asistencia' (/home/ubuntu/prototipo_web/recursosweb/src/models/asistencia.py)
[2025-05-21 08:35:33 -0400] [28104] [INFO] Worker exiting (pid: 28104)
[2025-05-21 08:35:34 -0400] [28103] [ERROR] Worker (pid:28104) exited with code 3
[2025-05-21 08:35:34 -0400] [28103] [ERROR] Shutting down: Master
[2025-05-21 08:35:34 -0400] [28103] [ERROR] Reason: Worker failed to boot.
[2025-05-21 08:38:03 -0400] [28561] [INFO] Starting gunicorn 21.2.0
[2025-05-21 08:38:03 -0400] [28561] [INFO] Listening at: http://0.0.0.0:5000 (28561)
[2025-05-21 08:38:03 -0400] [28561] [INFO] Using worker: sync
[2025-05-21 08:38:03 -0400] [28563] [INFO] Booting worker with pid: 28563
[2025-05-21 08:38:04 -0400] [28563] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.11/dist-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.11/dist-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/prototipo_web/recursosweb/wsgi.py", line 17, in <module>
    app = create_app()
          ^^^^^^^^^^
NameError: name 'create_app' is not defined
[2025-05-21 08:38:04 -0400] [28563] [INFO] Worker exiting (pid: 28563)
[2025-05-21 08:38:04 -0400] [28561] [ERROR] Worker (pid:28563) exited with code 3
[2025-05-21 08:38:04 -0400] [28561] [ERROR] Shutting down: Master
[2025-05-21 08:38:04 -0400] [28561] [ERROR] Reason: Worker failed to boot.
[2025-05-21 08:39:30 -0400] [29160] [INFO] Starting gunicorn 21.2.0
[2025-05-21 08:39:30 -0400] [29160] [INFO] Listening at: http://0.0.0.0:5000 (29160)
[2025-05-21 08:39:30 -0400] [29160] [INFO] Using worker: sync
[2025-05-21 08:39:30 -0400] [29161] [INFO] Booting worker with pid: 29161
[2025-05-21 08:43:07 -0400] [29161] [INFO] Worker exiting (pid: 29161)
[2025-05-21 08:43:07 -0400] [29160] [INFO] Handling signal: term
[2025-05-21 08:43:07 -0400] [29160] [ERROR] Worker (pid:29161) was sent SIGTERM!
[2025-05-21 08:43:07 -0400] [29160] [INFO] Shutting down: Master
[2025-05-21 08:43:07 -0400] [29683] [INFO] Starting gunicorn 21.2.0
[2025-05-21 08:43:07 -0400] [29683] [INFO] Listening at: http://0.0.0.0:5000 (29683)
[2025-05-21 08:43:07 -0400] [29683] [INFO] Using worker: sync
[2025-05-21 08:43:07 -0400] [29684] [INFO] Booting worker with pid: 29684
[2025-05-21 09:23:24 -0400] [29683] [CRITICAL] WORKER TIMEOUT (pid:29684)
[2025-05-21 09:23:24 -0400] [29684] [INFO] Worker exiting (pid: 29684)
[2025-05-21 09:23:24 -0400] [29683] [ERROR] Worker (pid:29684) exited with code 1
[2025-05-21 09:23:24 -0400] [29683] [ERROR] Worker (pid:29684) exited with code 1.
[2025-05-21 09:23:24 -0400] [30425] [INFO] Booting worker with pid: 30425
[2025-05-22 03:22:37 -0400] [29683] [CRITICAL] WORKER TIMEOUT (pid:30425)
[2025-05-22 03:22:37 -0400] [30425] [INFO] Worker exiting (pid: 30425)
[2025-05-22 03:22:37 -0400] [29683] [ERROR] Worker (pid:30425) exited with code 1
[2025-05-22 03:22:37 -0400] [29683] [ERROR] Worker (pid:30425) exited with code 1.
[2025-05-22 03:22:37 -0400] [31115] [INFO] Booting worker with pid: 31115
[2025-05-22 03:51:45 -0400] [29683] [CRITICAL] WORKER TIMEOUT (pid:31115)
[2025-05-22 03:51:45 -0400] [31115] [INFO] Worker exiting (pid: 31115)
[2025-05-22 03:51:46 -0400] [29683] [ERROR] Worker (pid:31115) exited with code 1
[2025-05-22 03:51:46 -0400] [29683] [ERROR] Worker (pid:31115) exited with code 1.
[2025-05-22 03:51:46 -0400] [32402] [INFO] Booting worker with pid: 32402
[2025-05-22 04:16:34 -0400] [32402] [INFO] Worker exiting (pid: 32402)
[2025-05-22 04:16:34 -0400] [29683] [INFO] Handling signal: term
[2025-05-22 04:16:35 -0400] [29683] [INFO] Shutting down: Master
