[2025-05-21 08:08:10 -0400] [24221] [INFO] Starting gunicorn 21.2.0
[2025-05-21 08:08:10 -0400] [24221] [INFO] Listening at: http://0.0.0.0:5000 (24221)
[2025-05-21 08:08:10 -0400] [24221] [INFO] Using worker: sync
[2025-05-21 08:08:10 -0400] [24222] [INFO] Booting worker with pid: 24222
[2025-05-21 08:08:10 -0400] [24222] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.11/dist-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.11/dist-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/prototipo_web/recursosweb/wsgi.py", line 9, in <module>
    from src.main import app
  File "/home/ubuntu/prototipo_web/recursosweb/src/main.py", line 43, in <module>
    from src.routes.vacaciones import vacaciones_bp
ModuleNotFoundError: No module named 'src.routes.vacaciones'
[2025-05-21 08:08:10 -0400] [24222] [INFO] Worker exiting (pid: 24222)
[2025-05-21 08:08:11 -0400] [24221] [ERROR] Worker (pid:24222) exited with code 3
[2025-05-21 08:08:11 -0400] [24221] [ERROR] Shutting down: Master
[2025-05-21 08:08:11 -0400] [24221] [ERROR] Reason: Worker failed to boot.
